services:
  postgres:
    container_name: todo_app_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - todo_app_network
  rest_api:
    build: .
    ports:
      - '8080:8080'
    networks:
      - todo_app_network
    depends_on:
      postgres:
        condition: service_started
volumes:
  postgres:
networks:
  todo_app_network:
    driver: bridge

